brightideas/config/routes.rb
Brightideas::Application.routes.draw do
  
  get "users/view"

  devise_for :users

  get "ideas/new"

  get "ideas/index"

  get "ideas/view"

  get "ideas/like"

  get "ideas/dislike"

  get "ideas/edit"

  get "ideas/update"

  match 'credits' => 'ideas#credits', :as => :credits
  
  resources :ideas
  root :to => "ideas#index"
  

end

brightideas/app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, :description, :presence => true
  validates :title, :uniqueness => true
  validates :like, :numericality => {:greater_than => -1}
  validates :dislike, :numericality => {:greater_than => -1}

  belongs_to :user

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end
# == Schema Information
#
# Table name: ideas
#
#  id          :integer         not null, primary key
#  title       :text
#  description :text
#  like        :integer
#  dislike     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#

brightideas/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :email, :about
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :about

  has_many :ideas
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  about                  :text
#

brightideas/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  respond_to :html, :xml
  helper_method :sort_column, :sort_direction

  def new
    @idea = Idea.new
    @title = "New Idea"

    respond_with(@idea)
  end

  def show
    @idea = Idea.find(params[:id])
    @owner = User.find(@idea.user_id)
    @title = "Show Idea"

    respond_with(@idea)
  end

  def create
    @idea = Idea.new(params[:idea])
    @idea.user_id = current_user.id
    @idea.like = 0
    @idea.dislike = 0
    @title = "Create a new idea"

    if @idea.save
      flash[:notice] = 'Idea was successfully saved.'
    else
      render :action => :new
    end
    respond_with(@idea)
  end

  def index
    @ideas = Idea.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    @title = "All Ideas"
    respond_with(@ideas)
  end

  def edit
    @idea ||= Idea.find(params[:id])
    @title = "Edit"
    respond_with(@idea)
  end

  def update
    @idea = Idea.find(params[:id])
    @title = "Update"

    if @idea.update_attributes(params[:idea])
      flash[:notice] = 'Idea was successfully updated.'
    end
    respond_with(@idea)
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:notice] = "Successfully deleted the idea"
    respond_with(@idea)
  end

  def like
    @idea = Idea.find(params[:id])
    @idea.like = @idea.like + 1
    @idea.save

    redirect_to ideas_path
  end

  def dislike
    @idea = Idea.find(params[:id])
    @idea.dislike = @idea.dislike + 1
    @idea.save

    redirect_to ideas_path
  end

  def credits
    @title = "Credits"
    respond_with(@idea)
  end

  private

  def sort_column
    Idea.column_names.include?(params[:sort]) ? params[:sort] : "like"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

brightideas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def view
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
end

brightideas/app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end

  def title
    base_title = "Bright Ideas"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

brightideas/app/helpers/user_helper.rb
module UserHelper
end

brightideas/app/views/ideas/_ideas.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table>
  <tr>
    <th><%= sortable "idea", "Ideas" %></th>
    <th><%= sortable "like", "Likes" %></th>
    <th><%= sortable "dislike", "Dislikes" %></th>
    <th><%= sortable "created_at","Submitted At",  %></th>
  </tr>
  <% @ideas.each do |idea| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td class="list_description">
          <dl>
            <dt><%= idea.title %></dt>
            <dd><%= truncate(strip_tags(idea.description),
                             :length => 80) %></dd>
            <%= link_to 'Like', :controller => "ideas", :id => idea,:action => "like" %>
            <%= link_to 'Dislike', :controller => "ideas", :id => idea,:action => "dislike" %>
            <%= link_to 'Show', idea %>
            <%= link_to 'Destroy', idea,
                        :confirm => 'Are you sure?',
                        :method => :delete %>
          </dl>
        </td>
        <td><%= idea.like %></td>
        <td><%= idea.dislike %></td>
        <td><%= idea.created_at %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @ideas %>

brightideas/app/views/ideas/create.js.erb
/**
 * Created by JetBrains RubyMine.
 * User: nishithnand
 * Date: 9/23/11
 * Time: 11:21 PM
 * To change this template use File | Settings | File Templates.
 */
$('body').html("<h1><%= escape_javascript(@idea.title) %></h1>").append("<%= escape_javascript(@idea.description) %>");

brightideas/app/views/ideas/credits.html.erb
<ul>
  <li><%= link_to "Rails casts", "http://railscasts.com/" %></li>
  <li><%= link_to "Logo", "http://www.flickr.com/photos/smemon/4414374988/" %></li>
  <li><%= link_to "Twitter Bootstrap", "http://twitter.github.com/bootstrap/" %></li>
  <li><%= link_to "Devise", "https://github.com/plataformatec/devise" %></li>
  <li><%= link_to "RoR guide", "http://guides.rubyonrails.org/" %></li>
  <li><%= link_to "RoR tutorials", "http://ruby.railstutorial.org/" %></li>
</ul>

brightideas/app/views/ideas/edit.html.erb
<h1>Edit idea</h1>
<%= render :partial => "layouts/idea_form"%>

<br />

brightideas/app/views/ideas/index.html.erb
<h1>All Ideas</h1>
<%= form_tag ideas_path, :method => 'get', :id => "ideas_search" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
    <div id="ideas"><%= render 'ideas' %></div>
<% end %>


<% if not user_signed_in? %>
    <%= link_to "Sign up now!", new_user_registration_path, :class => "big_button round" %>
<% else %>
    <%= link_to "Have an idea?", new_idea_path, :class => "big_button round" %>
<% end %>

brightideas/app/views/ideas/index.js.erb
$("#ideas").html("<%= escape_javascript(render("ideas")) %>");

brightideas/app/views/ideas/show.html.erb
<div id="idea" class="idea">
  <div id="idea_title">
    <%= @idea.title %>
  </div>
  <br />
  <div id="idea_description" class="idea_description">
    <%= @idea.description %>
  </div>
  <br />
  <div id="idea_owner" class="idea_owner">
    <%= link_to @owner.name, :controller => "users", :action => "view",:id => @idea.user_id%>
  </div>
  <div id="likes" class="likes">
    <%= @idea.like %> people like this idea.
  </div>
  <div id="dislikes" class="dislikes">
    <%= @idea.dislike %> people dislike this idea.
  </div>
</div>

brightideas/app/views/layouts/_header.html.erb
<header>
    <% logo = image_tag("ideas-300x103.jpg", :alt => "Bright ideas", :class => "round") %>
    <%= link_to logo, root_path %>
    <nav class="round">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Credits", credits_path %></li>
        </ul>
    </nav>
</header>

brightideas/app/views/layouts/_idea_form.html.erb
<%= form_for(@idea, :remote => true) do |f| %>
    <div id="idea" class="idea">
      <div id="idea_title" class="idea_title">
        <%= f.label :title %><br />
        <%= f.text_field :title, :size => "100" %>
      </div>
      <div id="idea_description" class="idea_description">
        <%= f.label :description %><br />
        <%= f.text_area :description, :cols => "100", :rows => "5" %>
      </div>
      <%= f.submit "Save Idea" %>
    </div>
<% end %>

brightideas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'rails' %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<%= render 'devise/menu/login_items' %>
		<section class="round">
			<% if notice %>
			<p class="notice"><%= notice %></p>
			<% end %>
			<% if alert %>
			<p class="alert"><%= alert %></p>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

brightideas/app/views/users/view.html.erb
<div id="user" class="user">
  <div id="user_title">
    <%= @user.name %>
  </div>
  <br />
  <div id="user_about" class="user_about">
    <%= @user.about %>
  </div>
  <br />
  <div id="user_email" class="user_email">
    <%= @user.email %>
  </div>
</div>